name: Terraform with actions

on:
  workflow_dispatch:
    inputs:
      actions:
        description: 'Terraform action to perform (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
          - skip
      directory:
        description: 'Terraform directory to run (eg: vpc, eks)'
        required: true
        default: 'vpc'

jobs:
    infra:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ${{ github.event.inputs.directory }}
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: aws configure
          uses: aws-actions/configure-aws-credentials@v4.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1
            
        - name: terraform setup
          uses: hashicorp/setup-terraform@v3.1.2
          with:
            terraform_version: '1.11.4'
        
        - name: terraform init
          run: terraform init
          
        - name: terraform plan
          if: ${{ github.event.inputs.actions == 'apply' }}
          run: terraform plan

        - name: terraform apply
          if: ${{ github.event.inputs.actions == 'apply' }}
          run: terraform apply --auto-approve
          
        - name: terraform destroy
          if: ${{ github.event.inputs.actions == 'destroy' }}
          run: terraform destroy --auto-approve