name: Terraform with actions

on:
  workflow_dispatch:

jobs:
    infra:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: aws configure
          uses: aws-actions/configure-aws-credentials@v4.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1
            
        - name: terraform setup
          uses: hashicorp/setup-terraform@v3.1.2
          with:
            terraform_version: '1.11.4'

        